name: "People Map Plus Backend"
version: "0.1.1"
slug: "people_map_plus"
description: "Backend API and indexing service for People Map Plus card"
url: "https://github.com/maxminsk/HaMapAddon"
startup: services
boot: auto
init: false
hassio_api: true
homeassistant_api: true
ingress: true
ingress_port: 8099
panel_icon: mdi:map-marker-path
panel_title: People Map Plus
arch:
  - amd64
  - aarch64
  - armv7
image: "ghcr.io/maxminsk/people-map-plus-addon-{arch}"
map:
  - "media:rw"
  - "config:rw"
options:
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
